# Generated by Django 2.2.6 on 2019-10-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BJ_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(verbose_name='date')),
                ('choice', models.CharField(choices=[('hit', 'Hit'), ('stand', 'Stand'), ('double', 'Double'), ('insurrance', 'Insurrance'), ('split', 'Split')], max_length=10)),
            ],
        ),
    ]
